const testtasklist = [

     {
       "TaskId": 7,
       "AssignedTo": "Ian",
       "Title": "Test",
       "Notes": "",
       "DueDate": null,
       "Status": "COMPLETE",
       "CreationDate": "2019-08-09 21:08:53",
       "CompletionDate": "2019-08-09 21:08:56",
       "Priority": 0,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Ian",
       "References": []
     },
     {
       "TaskId": 16,
       "AssignedTo": "Ian",
       "Title": "Plz change this signed contract",
       "Notes": "Plz update to ONE payment, and update map with big blurb that says \"LIGHT ICE MELTER APPLIED ON ALL AREAS\" - you can also input this statement into the Site Notes - please let me know when done so I can send her the invoice :)",
       "DueDate": null,
       "Status": "COMPLETE",
       "CreationDate": "2019-08-22 20:50:43",
       "CompletionDate": "2019-08-26 14:20:30",
       "Priority": 2,
       "Location": "",
       "isComplete": 1,
       "Creator": "Mikhail",
       "Manager": "Mikhail",
       "Type": "Task",
       "Completer": "Ian",
      
     {
       "TaskId": 20,
       "AssignedTo": "Ian",
       "Title": "This contract wont create ;( errors out on create process - plz check in :)",
       "Notes": "",
       "DueDate": "2019-08-28 12:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2019-08-24 03:24:52",
       "CompletionDate": "2019-08-26 22:50:41",
       "Priority": 1,
       "Location": "",
       "isComplete": 1,
       "Creator": "Mikhail",
       "Manager": "Mikhail",
       "Type": "Task",
       "Completer": "Ian",
       "References": [
         {
           "id": 76,
           "TaskId": 20,
           "Type": "Quote",
           "Reference": "2019-R0042",
           "Label": "2019-R0042 1500 Royal York Rd"
         },
         {
           "id": 77,
           "TaskId": 20,
           "Type": "Contact",
           "Reference": "1038",
           "Label": "Albert Benudiz"
         }
       ]
     },
     {
       "TaskId": 38,
       "AssignedTo": "Ian",
       "Title": "Test Past Due Task",
       "Notes": "asdff",
       "DueDate": "2019-09-02 08:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2019-09-03 20:05:27",
       "CompletionDate": "2019-09-04 20:23:38",
       "Priority": 1,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Mikhail",
       "References": []
     },
     {
       "TaskId": 141,
       "AssignedTo": "Ian",
       "Title": "This quote refuses to send for some reason, errors out on MC",
       "Notes": "plz investigate and send ;)",
       "DueDate": "2019-09-11 08:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2019-09-11 16:17:37",
       "CompletionDate": "2019-09-11 16:32:31",
       "Priority": 2,
       "Location": "1947-2013 Finch Avenue West, Toronto, ON, Canada",
       "isComplete": 1,
       "Creator": "Mikhail",
       "Manager": "Mikhail",
       "Type": "Task",
       "Completer": "Ian",
       "References": [
         {
           "id": 554,
           "TaskId": 141,
           "Type": "Quote",
           "Reference": "2019-A1975",
           "Label": "2019-A1975 1947-2013 Finch Avenue West"
         },
         {
           "id": 555,
           "TaskId": 141,
           "Type": "Contact",
           "Reference": "7115",
           "Label": "Bella"
         }
       ]
     },
     {
       "TaskId": 245,
       "AssignedTo": "Ian",
       "Title": "Cant create quote for some reason! plz create and send!",
       "Notes": "",
       "DueDate": "2019-09-20 08:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2019-09-20 03:37:45",
       "CompletionDate": "2019-09-20 16:24:14",
       "Priority": 1,
       "Location": "63 Highland Ave, Toronto, ON, Canada",
       "isComplete": 1,
       "Creator": "Mikhail",
       "Manager": "Mikhail",
       "Type": "Task",
       "Completer": "Ian",
       "References": [
         {
           "id": 1014,
           "TaskId": 245,
           "Type": "Quote",
           "Reference": "2019-N4945",
           "Label": "2019-N4945 63 Highland Ave"
         },
         {
           "id": 1015,
           "TaskId": 245,
           "Type": "Contact",
           "Reference": "7871",
           "Label": "Jennifer "
         }
       ]
     },
     {
       "TaskId": 248,
       "AssignedTo": "Ian",
       "Title": "It was this one that I couldn't send",
       "Notes": "",
       "DueDate": "2019-09-20 08:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2019-09-20 16:29:44",
       "CompletionDate": "2019-09-20 16:50:22",
       "Priority": 1,
       "Location": "34 Hopperton Drive, Toronto, ON, Canada",
       "isComplete": 1,
       "Creator": "Mikhail",
       "Manager": "Mikhail",
       "Type": "Task",
       "Completer": "Ian",
       "References": [
         {
           "id": 1026,
           "TaskId": 248,
           "Type": "Quote",
           "Reference": "2019-N4942",
           "Label": "2019-N4942 34 Hopperton Drive"
         },
         {
           "id": 1027,
           "TaskId": 248,
           "Type": "Contact",
           "Reference": "7868",
           "Label": "Ron Segev "
         }
       ]
     },
     {
       "TaskId": 249,
       "AssignedTo": "Ian",
       "Title": "Error",
       "Notes": "Params\n Object\nFunction: \"createQuote\"\n Params: Object\nResult\nundefined\nMessage\n\"\n\\nWarning:  array_filter() expects parameter 1 to be array, null given in /home/public/include/FileManager.php on line 61\n\\n\n\\nWarning:  array_values() expects parameter 1 to be array, null given in /home/public/include/FileManager.php on line 61\n\\n\n\\nWarning:  array_filter() expects parameter 1 to be array, null given in /home/public/include/FileManager.php on line 76\n\\n\n\\nWarning:  array_values() expects parameter 1 to be array, null given in /home/public/include/FileManager.php on line 76\n\\n{\\\"success\\\":true,\\\"results\\\":\\\"output\\\\/(2019-A2240) 1 & 3 Resurrection Rd.pdf\\\",\\\"error\\\":\\\"\\\",\\\"message\\\":\\\"\\\"}\"",
       "DueDate": "2019-09-20 08:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2019-09-20 16:53:50",
       "CompletionDate": "2019-09-21 04:14:31",
       "Priority": 2,
       "Location": "1 Resurrection Rd, Toronto, ON, Canada",
       "isComplete": 1,
       "Creator": "Mikhail",
       "Manager": "Mikhail",
       "Type": "Task",
       "Completer": "Mikhail",
       "References": [
         {
           "id": 1030,
           "TaskId": 249,
           "Type": "Quote",
           "Reference": "2019-A2240",
           "Label": "2019-A2240 1 Resurrection Rd"
         },
         {
           "id": 1031,
           "TaskId": 249,
           "Type": "Contact",
           "Reference": "7072",
           "Label": "Al Nakrosius"
         }
       ]
     },
     {
       "TaskId": 260,
       "AssignedTo": "Ian",
       "Title": "angular2-signature pad bug fix",
       "Notes": "this._signaturePad = new SignaturePad.default(this._canvas); \nline 60\nsignature-pad.component.js\nhttps://github.com/dimpu/angular2-signature-pad",
       "DueDate": "2019-09-24 08:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2019-09-23 23:20:15",
       "CompletionDate": "2019-09-25 23:03:46",
       "Priority": 3,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Ian",
       "References": []
     },
     {
       "TaskId": 280,
       "AssignedTo": "Ian",
       "Title": "Cannot create these quotes no matter what I try with the map file optimization",
       "Notes": "Plz create and send!",
       "DueDate": "2019-09-27 08:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2019-09-27 20:21:40",
       "CompletionDate": "2019-09-29 14:28:24",
       "Priority": 2,
       "Location": "",
       "isComplete": 1,
       "Creator": "Mikhail",
       "Manager": "Mikhail",
       "Type": "Task",
       "Completer": "Ian",
       "References": [
         {
           "id": 1143,
           "TaskId": 280,
           "Type": "Contact",
           "Reference": "7994",
           "Label": "Benjamin Peleg "
         },
         {
           "id": 1144,
           "TaskId": 280,
           "Type": "Quote",
           "Reference": "2019-N5100",
           "Label": "2019-N5100 312 Dolomite Drive"
         },
         {
           "id": 1145,
           "TaskId": 280,
           "Type": "Quote",
           "Reference": "2019-N5101",
           "Label": "2019-N5101 1416 Centre Street"
         }
       ]
     },
     {
       "TaskId": 373,
       "AssignedTo": "Ian",
       "Title": "employee export",
       "Notes": "",
       "DueDate": "2019-11-14 07:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2019-11-11 17:16:21",
       "CompletionDate": "2019-11-18 13:37:39",
       "Priority": 3,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Ian",
       "References": []
     },
     {
       "TaskId": 374,
       "AssignedTo": "Ian",
       "Title": "employee timesheets export",
       "Notes": "",
       "DueDate": "2019-11-15 07:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2019-11-11 17:16:42",
       "CompletionDate": "2019-11-18 13:37:53",
       "Priority": 3,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Ian",
       "References": []
     },
     {
       "TaskId": 375,
       "AssignedTo": "Ian",
       "Title": "Monthy Logs Victoria Hefforn",
       "Notes": "",
       "DueDate": "2019-12-01 07:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2019-11-11 17:17:27",
       "CompletionDate": "2019-12-02 23:02:13",
       "Priority": 2,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Ian",
       "References": []
     },
     {
       "TaskId": 387,
       "AssignedTo": "Ian",
       "Title": "Vikki Hefforn December logs",
       "Notes": "",
       "DueDate": "2020-01-01 07:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2019-12-02 23:02:11",
       "CompletionDate": "2020-01-02 20:32:30",
       "Priority": 2,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Ian",
       "References": []
     },
     {
       "TaskId": 393,
       "AssignedTo": "Ian",
       "Title": "Vikki Hefforn Janyary Logs",
       "Notes": "",
       "DueDate": "2020-02-01 07:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2020-01-02 20:32:21",
       "CompletionDate": "2020-02-03 21:50:38",
       "Priority": 2,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Ian",
       "References": []
     },
     {
       "TaskId": 395,
       "AssignedTo": "Ian",
       "Title": "Pick up key fob at BJL 782 King Street West",
       "Notes": "",
       "DueDate": "2020-01-29 07:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2020-01-27 15:17:15",
       "CompletionDate": "2020-02-01 23:57:53",
       "Priority": 3,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Ian",
       "References": []
     },
     {
       "TaskId": 396,
       "AssignedTo": "Ian",
       "Title": "Fix getACtivePayPeriod code on two servers",
       "Notes": "",
       "DueDate": "2020-02-02 07:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2020-02-01 23:58:34",
       "CompletionDate": "2020-02-03 16:01:38",
       "Priority": 3,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Ian",
       "References": []
     },
     {
       "TaskId": 397,
       "AssignedTo": "Ian",
       "Title": "fix slavin hours fix stepan hours",
       "Notes": "",
       "DueDate": "2020-02-08 07:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2020-02-07 07:19:59",
       "CompletionDate": "2020-02-07 22:01:01",
       "Priority": 2,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Ian",
       "References": []
     },
     {
       "TaskId": 398,
       "AssignedTo": "Ian",
       "Title": "fix dolores hours",
       "Notes": "",
       "DueDate": "2020-02-08 07:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2020-02-07 14:30:34",
       "CompletionDate": "2020-02-11 16:05:07",
       "Priority": 2,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Ian",
       "References": []
     },
     {
       "TaskId": 399,
       "AssignedTo": "Ian",
       "Title": "fix kyle hours",
       "Notes": "",
       "DueDate": "2020-02-14 07:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2020-02-13 06:42:59",
       "CompletionDate": "2020-02-14 04:59:19",
       "Priority": 2,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Ian",
       "References": []
     },
     {
       "TaskId": 400,
       "AssignedTo": "Ian",
       "Title": "fix anthony kimber huors",
       "Notes": "",
       "DueDate": "2020-02-13 07:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2020-02-14 04:59:18",
       "CompletionDate": "2020-02-17 20:25:21",
       "Priority": 3,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Ian",
       "References": []
     },
     {
       "TaskId": 401,
       "AssignedTo": "Ian",
       "Title": "review nathanial hours",
       "Notes": "",
       "DueDate": "2020-02-14 07:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2020-02-14 05:01:18",
       "CompletionDate": "2020-02-14 17:25:04",
       "Priority": 2,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Ian",
       "References": []
     },
     {
       "TaskId": 402,
       "AssignedTo": "Ian",
       "Title": "Check eportal submit your token here link",
       "Notes": "",
       "DueDate": "2020-02-19 07:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2020-02-18 07:11:24",
       "CompletionDate": "2020-02-19 16:29:27",
       "Priority": 3,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Ian",
       "References": []
     },
     {
       "TaskId": 2,
       "AssignedTo": "Mikhail",
       "Title": "I have been using this for tests",
       "Notes": "Do we need this to be original owner?",
       "DueDate": "2019-07-18 00:00:00",
       "Status": "CLOSED",
       "CreationDate": "2019-07-17 23:14:51",
       "CompletionDate": null,
       "Priority": 2,
       "Location": "Toronto",
       "isComplete": 1,
       "Creator": "",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": null
     },
     {
       "TaskId": 36,
       "AssignedTo": "Mikhail",
       "Title": "Please go into your google calendar and delete event \"Test Meeting Invite\", cuz it's broken",
       "Notes": "",
       "DueDate": "2019-09-04 08:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2019-09-03 16:58:12",
       "CompletionDate": "2019-09-04 19:10:44",
       "Priority": 0,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Mikhail"
     },
     {
       "TaskId": 61,
       "AssignedTo": "Mikhail",
       "Title": "Calendar Sign up. 2-3pm please!",
       "Notes": "Matt's is setup",
       "DueDate": "2019-09-05 08:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2019-09-05 11:03:20",
       "CompletionDate": "2019-09-05 18:36:14",
       "Priority": 2,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Mikhail"
     },
     {
       "TaskId": 209,
       "AssignedTo": "Mikhail",
       "Title": "Please make sure your Compression Settings in adobe illustrator are set to PDF 1.4.",
       "Notes": "We are having some troubles with maps being added to the quotes. The suggested fix is to use PDF 1.4 compression settings for saving maps. You can start a new preset with these settings.",
       "DueDate": "2019-09-18 08:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2019-09-17 17:35:22",
       "CompletionDate": "2019-09-20 01:22:25",
       "Priority": 2,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Mikhail"
     },
     {
       "TaskId": 10,
       "AssignedTo": "George",
       "Title": "Please see two new statuses \"Declined\" & \"Do Not Contact\"",
       "Notes": "",
       "DueDate": null,
       "Status": "COMPLETE",
       "CreationDate": "2019-08-20 19:57:48",
       "CompletionDate": "2019-08-21 23:12:15",
       "Priority": 1,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Mikhail"
     },
     {
       "TaskId": 35,
       "AssignedTo": "George",
       "Title": "See new Status 'personal follow-up sent'",
       "Notes": "",
       "DueDate": null,
       "Status": "COMPLETE",
       "CreationDate": "2019-08-30 16:14:03",
       "CompletionDate": "2019-08-31 04:18:40",
       "Priority": 0,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Mikhail"
     },
     {
       "TaskId": 208,
       "AssignedTo": "Matt",
       "Title": "Please make sure your Compression Settings in adobe illustrator are set to PDF 1.4.",
       "Notes": "We are having some troubles with maps being added to the quotes. The suggested fix is to use PDF 1.4 compression settings for saving maps. You can start a new preset with these settings.",
       "DueDate": "2019-09-18 08:00:00",
       "Status": "COMPLETE",
       "CreationDate": "2019-09-17 17:35:03",
       "CompletionDate": "2019-09-17 18:02:21",
       "Priority": 2,
       "Location": "",
       "isComplete": 1,
       "Creator": "Ian",
       "Manager": "Ian",
       "Type": "Task",
       "Completer": "Matt"
     }
   ]